name: 构建可执行文件

on:
  push:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build_windows_push:
    name: 构建 (Windows / push)
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: 签出存储库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 构建可执行文件
        run: |
          echo "DATE=$(Get-Date -Format 'yyyyMMdd')" >> $env:GITHUB_ENV
          pyinstaller --noconsole --uac-admin --icon=./static/images/DouK-Downloader.ico --add-data "static:static" --add-data "locale:locale" --collect-all emoji main.py
        shell: pwsh

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: DouK-Downloader_Windows_${{ runner.arch }}_${{ env.DATE }}
          path: dist/main/

  build_matrix_manual:
    name: 构建 (手动 / ${{ matrix.os }})
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.optional }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            optional: false
          - os: windows-11-arm
            optional: true
          - os: macos-latest
            optional: true
          - os: macos-15-intel
            optional: true

    steps:
      - name: 签出存储库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 构建 Win 可执行文件
        if: runner.os == 'Windows'
        run: |
          echo "DATE=$(Get-Date -Format 'yyyyMMdd')" >> $env:GITHUB_ENV
          pyinstaller --noconsole --uac-admin --icon=./static/images/DouK-Downloader.ico --add-data "static:static" --add-data "locale:locale" --collect-all emoji main.py
        shell: pwsh

      - name: 构建 Mac 可执行文件
        if: runner.os == 'macOS'
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          pyinstaller --icon=./static/images/DouK-Downloader.icns --add-data "static:static" --add-data "locale:locale" --collect-all emoji main.py

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: DouK-Downloader_${{ runner.os }}_${{ runner.arch }}_${{ env.DATE }}
          path: dist/main/
